[options]
require_exact_inputs = true
allow_multi_creation = true


[[config.component]]
name = "[[:0:]]/[[:0:]].tsx"
append = false
contents = """
import { Text, View } from 'react-native';

const [[:0:]] = () => {
  return (
    <View>
      <Text>[[:0:]]</Text>
    </View>
  );
};
"""

[[config.component]]
name = "[[:0:]]/index.ts"
append = false
contents = "export { default } from \"./[[:0:]]\";"

[[config.component]]
name = "[[:0:]]/[[:0:]].styles.ts"
append = false
contents = """
import { ThemeType } from \"Wedgekit/Types\"

export type Styles = {};

export default (theme: ThemeType): Styles => ({ });
"""

[[config.component]]
name = "index.ts"
append = true
contents = "export { default as [[:0:]] } from \"./[[:0:]]\";"


[[config.test1]]
name = "test/[[:0:]]And[[:1:]].ts"
append = false
contents = "export const add = ([[:0:]]: number, [[:1:]]: number) => [[:0:]] + [[:1:]];"

[[config.test2]]
name = "test/test2.ts"
append = false
contents = "export const identity = (a) => a;"