# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Build
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --target=${{ matrix.target }} --release
      - name: Upload Build
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/${{ matrix.target }}/release/boilit
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
